apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitops-task
spec:
  params:
    - name: app-name
      type: string
    - name: version
      type: string
    - name: deploy-env
      type: string
      default: prod
  steps:
    - name: git-clone
      image: docker.io/alpine/git:v2.26.2
      script: |
        echo "DEBUG: APP: $(params.app-name), VERSION: $(params.version), DEPLOY_ENV: $(params.deploy-env)"
        git config --global user.email {{ .Values.email }}
        git config --global user.name {{ .Values.user }}
        git clone -b master --single-branch https://github.com/{{ .Values.user }}/{{ .Values.repo }}
        cd {{ .Values.repo }}
        git branch $(params.deploy-env)
        git checkout $(params.deploy-env)
    - name: update-deploy-file
      image: mikefarah/yq:3.3.4
      script: |
        yq w -i {{ .Values.repo }}/deploy/values.yaml.$(params.deploy-env) "apps(name==$(params.app-name)).version" $(params.version)
    - name: push-config-repo
      image: docker.io/alpine/git:v2.26.2
      script: |
        cd {{ .Values.repo }}
        git add .
        git commit -m "update $(params.app-name)"
        git push origin $(params.deploy-env) --force
  # workspaces:
  # - name: config-repo
