apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitops-task
spec:
  params:
    - name: app-name
      type: string
    - name: image-tag
      type: string
    - name: env
      type: string
      default: prod
  stepTemplate:
    env:
    - name: APP
      value: $(params.app-name)
    - name: VERSION
      value: $(params.image-tag)
    - name: DEPLOY_ENV
      value: $(params.env)
  steps:
    - name: git-clone
      image: docker.io/alpine/git:v2.26.2
      script: |
        echo "DEBUG: APP: $APP, VERSION: $VERSION, DEPLOY_ENV: $DEPLOY_ENV"
        git config --global user.email {{ .Values.config.email }}
        git config --global user.name {{ .Values.config.user }}
        git clone -b master --single-branch https://github.com/{{ .Values.config.user }}/{{ .Values.config.repo }}
        cd {{ .Values.config.repo }}
        git branch $DEPLOY_ENV
        git checkout $DEPLOY_ENV
    - name: update-deploy-file
      image: mikefarah/yq:3.3.4
      script: |
        yq w -i {{ .Values.config.repo }}/deploy/values.yaml.$DEPLOY_ENV "apps(name==$APP).version" $VERSION
    - name: push-config-repo
      image: docker.io/alpine/git:v2.26.2
      script: |
        cd {{ .Values.config.repo }}
        git add .
        git commit -m "update $APP"
        git push origin $DEPLOY_ENV --force
  # workspaces:
  # - name: config-repo