apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: image-exist-check
spec:
  params:
    - name: image-name
    - name: image-tag

  results:
    - name: exists
      description: if image exist true else false
  steps:
    - name: search-image
      image: curlimages/curl
      script: |
        curl --fail https://{{ .Values.dockerRepo.url }}/api/v2.0/projects/{{ .Values.dockerRepo.project }}/repositories/$(params.image-name)/artifacts/$(params.image-tag) \
        && REUSLT=yes || RESULT=no

        echo $RESULT | tee $(results.exists.path)
        