apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: source-to-image
spec:
  params:
    - name: pathToDockerFile
      type: string
      description: The path to the dockerfile to build
      default: $(resources.inputs.app-source.path)/Dockerfile
    - name: pathToContext
      type: string
      description: |
        The build context used by Kaniko
        (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
      default: $(resources.inputs.app-source.path)
    - name: exists
      type: string
      default: "no"
  resources:
    inputs:
      - name: app-source
        type: git
    outputs:
      - name: app-image
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.3.0-debug
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      script: |
        #!/busybox/sh

        if [ "$(params.exists)" = "no" ]

        then

          /kaniko/executor --dockerfile=$(params.pathToDockerFile)
          --destination=$(resources.outputs.app-image.url)
          --context=$(params.pathToContext)

        fi
