{{ range .Values.apps }}
{{ $fullname := printf "%s-%s" .name $.Values.global.env | trunc 63 | trimSuffix "-" }}
{{ $fullnamespace := printf "%s-%s" .namespace $.Values.global.env | trunc 63 | trimSuffix "-" }}

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ $fullname }}
  namespace: {{ $fullnamespace }}
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}
  replicas: {{ default 1  .replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      containers:
      - name: {{ $fullname }}
        image: "{{ $.Values.config.dockerRepo.url }}/{{ $fullname }}:{{ default "latest" .version  }}"
        imagePullPolicy: IfNotPresent
        {{ if .service }}
        ports:
        {{- range .service }}
          - containerPort: {{ .port }}
            name: {{ .name }}
        {{ end -}}
        {{ end }}
{{ end }}