{{- range .Values.apps }}
{{- if .service -}}
{{ $fullnamespace := printf "%s-%s" .namespace $.Values.global.env | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $fullnamespace }}
spec:
  type: ClusterIP
  ports:
{{ toYaml .service | nindent 2}}
  selector:
    app: {{ .name }}
{{- end -}}
{{ end -}}