{{- range .Values.apps }}
{{- if .service -}}
{{ $fullname := printf "%s-%s" .name $.Values.global.env | trunc 63 | trimSuffix "-" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  namespace: {{ .namespace }}
spec:
  type: ClusterIP
  ports:
{{ toYaml .service | nindent 2}}
  selector:
    app: {{ .name }}
{{- end -}}
{{ end -}}