apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitops-task
spec:
  params:
    - name: application-name
      type: string
    - name: git-revision
      type: string
  steps:
    - name: update-deploy
      image: mikefarah/yq:3.3.4
      command:
        - yq 
      args:
        - w
        - $(resources.inputs.app-source.path)/app/values.yaml
        - 'config.apps(name==$(params.application-name)).version'
        - $(params.git-revision)
    - name: push-config-repo
      image: docker.io/alpine/git:v2.26.2
      script: |
        cd $(resources.inputs.app-source.path)
        git config --global user.email {{ .Values.config.email }}
        git config --global user.name {{ .Values.config.user }}
        git commit -m "auto commit"
        git push
  workspaces:
  - name: config-repo