apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitops-task
spec:
  params:
    - name: app-name
      type: string
    - name: git-revision
      type: string
    - name: env
      type: string
      default: prod
  stepTemplate:
    env:
    - name: APP
      value: $(params.app-name)
    - name: VESION
      value: $(git-revision)
    - name: DEPLOY_ENV
      value: $(params.env)
  steps:
    - name: git-clone
      image: docker.io/alpine/git:v2.26.2
      script: |
        git config --global user.email {{ .Values.config.email }}
        git config --global user.name {{ .Values.config.user }}
        git clone https://github.com/{{ .Values.config.user }}/{{ .Values.config.repo }}
        cd {{ .Values.config.repo }}
        git branch $DEPLOY_ENV
        git checkout $DEPLOY_ENV
    - name: update-deploy-file
      image: mikefarah/yq:3.3.4
      command: [yq, w, -i]
      args: [{{ .Values.config.repo }}/app/values.yaml, config.apps(name==$APP).version, $VESION]
    - name: push-config-repo
      image: docker.io/alpine/git:v2.26.2
      script: |
        cd {{ .Values.config.repo }}
        git add .
        git commit -m "update $APP"
        git push
  # workspaces:
  # - name: config-repo