apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitops-task
spec:
  params:
    - name: application-name
      type: string
    - name: git-revision
      type: string
  resources:
    inputs:
      - name: app-config
        type: git
  steps:
    - name: update-deploy
      image: mikefarah/yq:3.3.4
      script: |
        yq w -i $(resources.inputs.app-config.path)/app/values.yaml config.apps(.name==$(params.application-name)).version $(params.git-revision)
        cat $(resources.inputs.app-config.path)/app/values.yaml
    - name: push-config-repo
      image: docker.io/alpine/git:v2.26.2
      script: |
        cd $(resources.inputs.app-config.path)
        git config --global user.email {{ .Values.config.email }}
        git config --global user.name {{ .Values.config.user }}
        git add .
        git commit -m "update $(params.application-name)"
        git push
  # workspaces:
  # - name: config-repo