apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  # workspaces
  # - name: config-repo
  params:
    - name: application-name
    - name: git-revision
  resources:
    - name: app-source
      type: git
    - name: app-config
      type: git
    - name: app-image
      type: image
  tasks:
    - name: build-and-publish-image
      resources:
        inputs:
          - name: app-source
            resource: app-source
        outputs:
          - name: app-image
            resource: app-image
      taskRef:
        kind: Task
        name: source-to-image
    - name: update-gitops-repo
      resources:
        inputs:
          - name: app-config
            resource: app-config
      taskRef:
        kind: Task
        name: gitops-task
      params:
      - name: application-name
        value: $(params.application-name)
      - name: git-revision
        value: $(params.git-revision)
      # workspaces:
      # - name: config-repo
      #   workspace: config-repo
    - name: argocd-sync-deployment
      params:
      - name: application-name
        value: $(params.application-name)
      - name: flags
        value: {{ .Values.config.argoCD.option | quote }}
      - name: argocd-version
        value: {{ .Values.config.argoCD.version }}
      runAfter:
        - build-and-publish-image
      taskRef:
        kind: Task
        name: argocd-task-sync-and-wait