apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: application-name
  resources:
    - name: source
      type: git
    - name: image
      type: image
  tasks:
    - name: build-and-publish-image
      resources:
        inputs:
          - name: source
            resource: source
        outputs:
          - name: image
            resource: image
      taskRef:
        kind: Task
        name: source-to-image
    - name: argocd-sync-deployment
      params:
        - name: application-name
          value: $(params.application-name)
        - name: flags
          value: {{ .Values.config.argoCD.option | quote }}
        - name: argocd-version
          value: {{ .Values.config.argoCD.version }}
      runAfter:
        - build-and-publish-image
      taskRef:
        kind: Task
        name: argocd-task-sync-and-wait